language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: MJOSIy0rYLknR1xboz8rMQ6fs+A7xDPnx9YtbseVlFHqxhe+pavxa4ksKVN4mKwA48SHJfpiPjufleBR1IoVBwXAL4AKHV+oV3UNGvNJYk6A1Odvv+dwtTpKA44FsbHWattuLAGL1H62YLNlRVTY8z+VwFUxPRywkzLYXSRmg12H4KSw218DxKzmx5FUAOpJBTR7UALOIkO7L5cctoI0RkomKw9A8VtF6nJtEQizsXJEUAhZNMa0yAFiQEmR4E3wHVyDONiLGC/wQKPsi8ScbEAFkjjcUV2DIYz69tACcIH9biPUsJtrq3MEafTGJoqShuDhHNpXcsP5Cvo32E+CjCfoBu++smHNtJmdn/TTOFaLBv9yE+dejzHHLz2Eea3P4wvmtlUc+M9YBdLxsRO0Hp1a+gCKPSvzxd+6S/N0m7DcrkPbu2akoI0ItlzfplVbsXkz2DXeKMVFp/cNmMKfwuUATalkyld+mdyrSmKxLG71q86qZPfovZFo4HclqSUouedD/NWum05s1p00ad9chyc4U/0f9SOtuKb9CE2RI2A0jOpTwBIOo2vinObWTd7FdyShvo0GoKonXK4oVs9Io/ZjthGqWpWFdIjmbb+orvy9j8dCuFFmmh1GU3wlvv/kne54xAadhWWcABdYL42kvdU6J2+PKUEB6r/ytuNgXbM=
  on:
    tags: true
    repo: ybenitezf/flask_cognitologin
    python: 3.8
